version: '3'
services:
  gateway:
    build:
      context: ./gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gateway:/go/src/github.com/sten-H/faas/gateway
    ports:
      - "80:80"
    environment:
      - DOCKER_API_VERSION=1.35  # docker client api will have version mismatch without this
  factorial:
    build:
      context: ./factorial
    volumes:
      - ./factorial:/go/src/github.com/sten-H/faas/factorial
    labels:
      - "faas.name=factorial"
      - "faas.port=8080"
      - "faas.path=factorial"
  ping:
    build:
      context: ./ping
    volumes:
      - ./ping:/go/src/github.com/sten-H/faas/ping
    labels:
      - "faas.name=ping"
      - "faas.port=8080"
      - "faas.path=ping"
